//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import javax.swing.*;
import java.util.ArrayList;

public class Interfaz extends JPanel {
    private JTabbedPane tabbedPane;
    private JPanel panelSolicitarCita;
    private JPanel panelConsultarCitas;
    private JPanel panelEliminarCitas;

    private JComboBox<String> comboBoxMedicos;
    private JComboBox<String> comboBoxTipoCita;
    private JComboBox<String> comboBoxFecha;
    private JComboBox<String> comboBoxHora;
    private JComboBox<String> comboBoxLugar;
    private JComboBox<String> comboBoxPaciente;
    private JButton botonSolicitar;

    private JTextArea areaCitas; // Para mostrar las citas consultadas
    private JComboBox<String> comboBoxCitasEliminar;
    private JButton botonEliminar;

    private ArrayList<Medico> medicos;
    private ArrayList<Paciente> pacientes;

    public Interfaz(ArrayList<Paciente> pacientes, ArrayList<Medico> medicos) {
        this.pacientes = pacientes;
        this.medicos = medicos;

        // Crear el JTabbedPane
        tabbedPane = new JTabbedPane();

        // Panel para solicitar cita
        panelSolicitarCita = crearPanelSolicitarCita();
        tabbedPane.addTab("Solicitar Cita", panelSolicitarCita);

        // Panel para consultar citas
        panelConsultarCitas = crearPanelConsultarCitas();
        tabbedPane.addTab("Consultar Citas", panelConsultarCitas);

        // Panel para eliminar citas
        panelEliminarCitas = crearPanelEliminarCitas();
        tabbedPane.addTab("Eliminar Citas", panelEliminarCitas);

        // Agregar el JTabbedPane al panel principal
        setLayout(new BorderLayout());
        add(tabbedPane, BorderLayout.CENTER);
    }

    private JPanel crearPanelSolicitarCita() {
        JPanel panel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5); // Margen alrededor de los componentes

        // Configuración de los componentes
        comboBoxMedicos = new JComboBox<>();
        comboBoxTipoCita = new JComboBox<>(new String[]{"General", "Radiografía", "Pediatra", "Psiquiatra", "Odontología"});
        comboBoxFecha = new JComboBox<>(new String[]{"23-11-2024", "25-10-2024", "01-12-2024"});
        comboBoxHora = new JComboBox<>(new String[]{"6:00 am", "8:00 am", "3:00 pm"});
        comboBoxLugar = new JComboBox<>(new String[]{"Hospital 1", "Hospital 2", "Hospital 3"});
        comboBoxPaciente = new JComboBox<>();

        botonSolicitar = new JButton("Solicitar Cita");

        // Llenar el JComboBox de médicos
        for (Medico medico : medicos) {
            comboBoxMedicos.addItem(medico.getNombre());
        }

        // Llenar el JComboBox de pacientes
        for (Paciente paciente : pacientes) {
            comboBoxPaciente.addItem(paciente.nombre);
        }

        // Añadir componentes al panel con GridBagLayout
        gbc.gridx = 0; gbc.gridy = 0; gbc.weightx = 0.5;
        panel.add(new JLabel("Seleccione un Médico:"), gbc);
        gbc.gridx = 1; gbc.gridy = 0; gbc.weightx = 1.0;
        panel.add(comboBoxMedicos, gbc);

        gbc.gridx = 0; gbc.gridy = 1;
        panel.add(new JLabel("Tipo de Cita:"), gbc);
        gbc.gridx = 1; gbc.gridy = 1;
        panel.add(comboBoxTipoCita, gbc);

        gbc.gridx = 0; gbc.gridy = 2;
        panel.add(new JLabel("Fecha:"), gbc);
        gbc.gridx = 1; gbc.gridy = 2;
        panel.add(comboBoxFecha, gbc);

        gbc.gridx = 0; gbc.gridy = 3;
        panel.add(new JLabel("Hora:"), gbc);
        gbc.gridx = 1; gbc.gridy = 3;
        panel.add(comboBoxHora, gbc);

        gbc.gridx = 0; gbc.gridy = 4;
        panel.add(new JLabel("Lugar:"), gbc);
        gbc.gridx = 1; gbc.gridy = 4;
        panel.add(comboBoxLugar, gbc);

        gbc.gridx = 0; gbc.gridy = 5;
        panel.add(new JLabel("Paciente:"), gbc);
        gbc.gridx = 1; gbc.gridy = 5;
        panel.add(comboBoxPaciente, gbc);

        gbc.gridx = 0; gbc.gridy = 6; gbc.gridwidth = 2; gbc.anchor = GridBagConstraints.CENTER;
        panel.add(botonSolicitar, gbc);

        // Acción del botón "Solicitar Cita"
        botonSolicitar.addActionListener(e -> solicitarCita());

        panel.setBorder(BorderFactory.createTitledBorder("Formulario de Solicitud de Cita"));

        return panel;
    }

    private JPanel crearPanelConsultarCitas() {
        JPanel panel = new JPanel(new BorderLayout());
        areaCitas = new JTextArea(10, 30);
        areaCitas.setEditable(false);

        JComboBox<String> comboBoxPacienteConsulta = new JComboBox<>();
        for (Paciente paciente : pacientes) {
            comboBoxPacienteConsulta.addItem(paciente.nombre);
        }

        JButton botonConsultar = new JButton("Consultar Citas");
        botonConsultar.addActionListener(e -> consultarCitas(comboBoxPacienteConsulta.getSelectedItem().toString()));

        JPanel topPanel = new JPanel();
        topPanel.add(new JLabel("Seleccione un Paciente:"));
        topPanel.add(comboBoxPacienteConsulta);
        topPanel.add(botonConsultar);

        panel.add(topPanel, BorderLayout.NORTH);
        panel.add(new JScrollPane(areaCitas), BorderLayout.CENTER);

        panel.setBorder(BorderFactory.createTitledBorder("Consulta de Citas"));

        return panel;
    }

    private JPanel crearPanelEliminarCitas() {
        JPanel panel = new JPanel(new GridLayout(3, 1));
        comboBoxCitasEliminar = new JComboBox<>();
        JButton botonCargarCitasEliminar = new JButton("Cargar Citas");
        botonCargarCitasEliminar.setPreferredSize(new Dimension(100, 30)); // Reducir tamaño del botón
        botonCargarCitasEliminar.setMargin(new Insets(5, 10, 5, 10)); // Ajustar margen

        botonCargarCitasEliminar.addActionListener(e -> cargarCitasParaEliminar());

        botonEliminar = new JButton("Eliminar Cita");
        botonEliminar.setPreferredSize(new Dimension(100, 30)); // Reducir tamaño del botón
        botonEliminar.setMargin(new Insets(5, 10, 5, 10)); // Ajustar margen
        botonEliminar.addActionListener(e -> eliminarCita());

        panel.add(comboBoxCitasEliminar);
        panel.add(botonCargarCitasEliminar);
        panel.add(botonEliminar);

        panel.setBorder(BorderFactory.createTitledBorder("Eliminación de Citas"));

        return panel;
    }

    private void solicitarCita() {
        String medicoSeleccionado = (String) comboBoxMedicos.getSelectedItem();
        String tipoCitaSeleccionado = (String) comboBoxTipoCita.getSelectedItem();
        String fechaSeleccionada = (String) comboBoxFecha.getSelectedItem();
        String horaSeleccionada = (String) comboBoxHora.getSelectedItem();
        String lugarSeleccionado = (String) comboBoxLugar.getSelectedItem();
        String pacienteSeleccionado = (String) comboBoxPaciente.getSelectedItem();

        for (Paciente paciente : pacientes) {
            if (paciente.nombre.equals(pacienteSeleccionado)) {
                Cita nuevaCita = new Cita(fechaSeleccionada, Integer.parseInt(horaSeleccionada.split(":")[0]), tipoCitaSeleccionado, lugarSeleccionado, getMedicoByName(medicoSeleccionado), paciente);
                paciente.solicitarCita(nuevaCita);
                JOptionPane.showMessageDialog(this, "Cita solicitada con éxito para " + paciente.nombre);
                return;
            }
        }

        JOptionPane.showMessageDialog(this, "Error al solicitar la cita.");
    }

    private void consultarCitas(String pacienteSeleccionado) {
        areaCitas.setText(""); // Limpiar el área de texto

        for (Paciente paciente : pacientes) {
            if (paciente.nombre.equals(pacienteSeleccionado)) {
                areaCitas.append("Citas de " + paciente.nombre + ":\n\n");
                for (Cita cita : paciente.citas) {
                    areaCitas.append("Fecha: " + cita.getFecha() + "\n");
                    areaCitas.append("Hora: " + cita.getHora() + "\n");
                    areaCitas.append("Tipo: " + cita.getTipoCita() + "\n");
                    areaCitas.append("Lugar: " + cita.getLugar() + "\n");
                    areaCitas.append("Médico: " + cita.getMedico().getNombre() + "\n");
                    areaCitas.append("----------------------------------------------------\n");
                }
                return;
            }
        }
        areaCitas.append("No se encontraron citas para " + pacienteSeleccionado);
    }

    private void cargarCitasParaEliminar() {
        String pacienteSeleccionado = (String) comboBoxPaciente.getSelectedItem();
        comboBoxCitasEliminar.removeAllItems(); // Limpiar el combo box

        for (Paciente paciente : pacientes) {
            if (paciente.nombre.equals(pacienteSeleccionado)) {
                for (Cita cita : paciente.citas) {
                    comboBoxCitasEliminar.addItem(cita.toString()); // Asegúrate de que Cita tenga un método toString() bien definido
                }
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "No se encontraron citas para " + pacienteSeleccionado);
    }

    private void eliminarCita() {
        String citaSeleccionada = (String) comboBoxCitasEliminar.getSelectedItem();

        if (citaSeleccionada != null) {
            String pacienteSeleccionado = (String) comboBoxPaciente.getSelectedItem();
            for (Paciente paciente : pacientes) {
                if (paciente.nombre.equals(pacienteSeleccionado)) {
                    for (Cita cita : new ArrayList<>(paciente.citas)) { // Usar una copia para evitar ConcurrentModificationException
                        if (cita.toString().equals(citaSeleccionada)) {
                            paciente.citas.remove(cita);
                            JOptionPane.showMessageDialog(this, "Cita eliminada con éxito.");
                            cargarCitasParaEliminar(); // Recargar citas
                            return;
                        }
                    }
                }
            }
            JOptionPane.showMessageDialog(this, "No se encontró la cita seleccionada.");
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una cita para eliminar.");
        }
    }

    private Medico getMedicoByName(String nombre) {
        for (Medico medico : medicos) {
            if (medico.getNombre().equals(nombre)) {
                return medico;
            }
        }
        return null; // Si no se encuentra el médico
    }
}
